# Generated by Django 4.2.16 on 2024-10-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('siteconfig', '0001_initial'), ('siteconfig', '0002_requiredcourses'), ('siteconfig', '0003_delete_heroimage'), ('siteconfig', '0004_heroimage')]

    dependencies = [
        ('ed', '0016_auto_20190825_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.course')),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.ImageField(upload_to='')),
                ('app', models.CharField(choices=[('default', 'default'), ('ed', 'ed'), ('vita', 'vita'), ('reports', 'reports')], default='default', max_length=10, unique=True)),
            ],
        ),
    ]
