# Generated by Django 4.2.15 on 2024-10-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_requiredcourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroImage',
        ),
    ]
