# Generated by Django 4.2.15 on 2024-10-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_delete_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.ImageField(upload_to='')),
                ('app', models.CharField(choices=[('default', 'default'), ('ed', 'ed'), ('vita', 'vita'), ('reports', 'reports')], default='default', max_length=10, unique=True)),
            ],
        ),
    ]
