# Generated by Django 2.1.1 on 2019-07-30 19:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0002_auto_20190723_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='narrative',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
