# Generated by Django 2.1.1 on 2019-10-08 20:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0015_menu_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
        ),
    ]
