name: Test Django

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27

    - name: Install Database
      env:
        DB_DATABASE: poetfolio_dev
        DB_USER: poetfolio
        DB_PASSWORD: devdevdev
      steps:
        - name: Set up MySQL
          run: |
            sudo /etc/init.d/mysql start
            mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }
    
    - name: Install Flake
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: nix build
        
    - name: Check Flake
      run: nix flake check

    - name: Run Migrations
      env:
        POETFOLIO_DB_HOST: 127.0.0.1
      run: |
        ./result/bin/python ./ekiree_dashboard/manage.py migrate

    - name: Test Poetfolio
      env:
        POETFOLIO_DB_HOST: 127.0.0.1
      run: |
        ./result/bin/python ./ekiree_dashboard/manage.py test poetfolio
